### ISSUE TITLE
PyPi installation error

### ISSUE THREAD

**Issue by MythHack** [MyKings/python-masscan#1]
PyPI does not have "compressed" on the compressed package "README.md" and CHANGELOG.md cause the installation to fail
`long_description=open('README.md').read() + "\n" + open('CHANGELOG.md').read(),`

**Comment by cr8ivecodesmith** [comment]
I have pull request #2 to temporarily fix this issue along with some additional data to the scan result.

If you want to try it, feel free to pip install directly from my repo:

```
pip install -U -I git+git://github.com/cr8ivecodesmith/python-masscan.git
```
