### ISSUE TITLE
How to use PortScannerYield?Got an error

### ISSUE THREAD

**Issue by liuyoyi** [MyKings/python-masscan#11]
`AttributeError: 'PortScanner' object has no attribute 'listscan'`

**Comment by MyKings** [comment]
@liuyoyi 
Provide script or scan parameters?

**Comment by MyKings** [comment]
I think you can add the following debug code in line 354 of the `masscan/masscan.py` script.

`asser type(masscan_err_keep_trace) is list, masscan_err`

The final effect might look like this :)

```
         assert type(masscan_err_keep_trace) is list, masscan_err

        if masscan_xml_output is not None:
             self._masscan_last_output = masscan_xml_output

**Comment by kw2583** [comment]
Encountering this same issue. Searching through the code, listscan is only found in one place, which is line 607, but listscan isn't actually implemented anywhere. From what I can tell, it should probably refer to all_hosts, but simply replacing listscan with all_hosts doesn't do the trick.
