### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by liuyoyi** [MyKings/python-masscan#26]
` File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/python-masscan/setup.py", line 21, in <module>

    long_description = readme_file.read()

  File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4267: ordinal not in range(128)`

**Comment by MyKings** [comment]
@liuyoyi 

Please execute the following command to provide the Python version.

```bash
$ python -V
```

**Comment by liuyoyi** [comment]
@MyKings 
`# python -V
Python 2.7.6
# 
`

**Comment by MyKings** [comment]
@liuyoyi Release version 0.1.6 to resolve this issue.
