### ISSUE TITLE
if the host is down it will throw an exception

### ISSUE THREAD

**Issue by 0c0c0f** [MyKings/python-masscan#3]
mas.scan('120.24.234.46')

![image](https://user-images.githubusercontent.com/34776076/34455863-3289dcea-edc3-11e7-9547-737b1f72edc5.png)

**Comment by MyKings** [comment]
This error is caused by 120.24.234.46 address unreasonable.

I try to ping, returns the following result:

```bash
$ ping 120.24.234.46 -c 3
PING 120.24.234.46 (120.24.234.46): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1

--- 120.24.234.46 ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
```

**Comment by Atavic** [comment]
Address has 0 hosts associated with it.
