### ISSUE TITLE
How to turn off DEBUG prints?

### ISSUE THREAD

**Issue by analyserdmz** [MyKings/python-masscan#32]
Hello,
it would be nice if the DEBUG prints of the library would be optional.

Is there a way of suppressing it?

**Comment by chppppp** [comment]
bumping this one! i am also trying to figure this out.

**Comment by chppppp** [comment]
So far the best solution I have is to comment out this line in masscan.py

https://github.com/MyKings/python-masscan/blob/master/masscan/masscan.py#L17

If you installed from pip as root it should be at `/usr/local/lib/python3.7/dist-packages/masscan/masscan.py` 

if you installed from pip as a regular user it should be at `/home/<YOUR USERNAME>/.local/lib/python3.7/site-packages/masscan/masscan.py`

**Comment by chppppp** [comment]
no wait, i lied. i put the wrong line above. I just edited it.

**Comment by trash-rabbit** [comment]
This worked for me:
```python
import masscan
import logging

masscan.logger.setLevel(logging.INFO)
```
