### ISSUE TITLE
probleme running masscan

### ISSUE THREAD

**Issue by alk99-abderrahman** [MyKings/python-masscan#33]
hello  i run the following code
`import masscan
mas = masscan.PortScanner()
mas.scan('172.0.8.78/24', ports='22,80,8080', arguments='--max-rate 1000')
print(mas.scan_result)`

i get the following error
` ```
"C:\Users\router-getway\PycharmProjects\untitled1\venv\Scripts\python.exe C:/Users/router-getway/PycharmProjects/untitled1/main.py
Traceback (most recent call last):
  File "C:/Users/router-getway/PycharmProjects/untitled1/main.py", line 2, in <module>
    mas = masscan.PortScanner()
  File "C:\Users\router-getway\PycharmProjects\untitled1\venv\lib\site-packages\masscan\masscan.py", line 128, in __init__
    'masscan program was not found in path. PATH is : {0}'.format(os.getenv('PATH'))
masscan.masscan.PortScannerError: 'masscan program was not found in path. PATH is : C:\\Users\\router-getway\\PycharmProjects\\untitled1\\venv\\Scripts;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\MATLAB\\MATLAB Production Server\\R2015a\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PuTTY\\;C:\\Users\\router-getway\\AppData\\Local\\Programs\\Python\\Python37;C:\\Users\\router-getway\\AppData\\Local\\Programs\\Python\\Python37\\Scripts;C:\\Program Files\\Java\\jre1.8.0_251\\bin;C:\\Program Files (x86)\\Nmap;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2020.1.2\\bin;'

Process finished with exit code 1"
```
 `

**Comment by MyKings** [comment]
It‘s recommended to use the linux system, the windows system is currently incompatible.
