### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by FuckAllWorld** [MyKings/python-masscan#34]
Out of memory: Kill process 15506 (python3)

我在使用的时候发现，程序因为内存不足，然后被kill掉了

之前机器是1G内存，后续我增加到4G，还是因为内存不足被kill

我使用-iL 里面有几万行ip/ip段

猜测是不是communicate()的原因，导致内存泄漏？

:-(

**Comment by MyKings** [comment]
你是扫描了一个B段么，如果是，那么建议拆分成C段，分别扫描。
