### ISSUE TITLE
masscan json output broken?

### ISSUE THREAD

**Issue by hegzploit** [MyKings/python-masscan#35]
I get my portnumbers as integers and not strings which breaks parsing it as a JSON object.
any workaround for this

**Comment by dk-0x89** [comment]
Yes this still happen, and would hope that they fix this little bug. :( 


Easyiest way to fix it:
nano /usr/local/lib/python3.6/dist-packages/masscan/masscan.py
edit line: 
port = int(dport.get('portid'))
to 
port = str(dport.get('portid'))
