### ISSUE TITLE
masscan.masscan.PortScannerError

### ISSUE THREAD

**Issue by alimoradi2020** [MyKings/python-masscan#36]
```
import masscan

mas = masscan.PortScanner()
mas.scan('172.0.8.78/24', ports='22,80,8080')
print(mas.scan_result)
```
'masscan program was not found in path. PATH is : {0}'.format(os.getenv('PATH'))
masscan.masscan.PortScannerError: 'masscan program was not found in path. PATH is : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

what is the problem?!
im using python3.6

**Comment by atsiami** [comment]
same here.

**Comment by kordup** [comment]
Same here.
From what I've read it's a PATH issue... I've attempted to use: mas = `masscan.PortScanner(masscan_search_path=('/usr/bin/masscan',))` but still no luck.
Let me know if anyone figures this out!

**Comment by kordup** [comment]
I resolved this issue by downloading masscan.py from this github and importing it directly (instead of through pip).

**Comment by Andydev503** [comment]
it still says the same im also on windows 10
