### ISSUE TITLE
masscan.masscan.PortScannerError

### ISSUE THREAD

**Issue by akcofficial** [MyKings/python-masscan#39]
masscan.masscan.PortScannerError: 'masscan program was not found in path. PATH is : C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem

How can i fix this ?

**Comment by MyKings** [comment]
Please check if the masscan program is installed, https://github.com/robertdavidgraham/masscan
