### ISSUE TITLE
python-masscan won't return scan object

### ISSUE THREAD

**Issue by zekiz774** [MyKings/python-masscan#47]
Code:
```python3
mas = masscan.PortScanner()
mas.scan("0.0.0.0/24", ports="25565", arguments="--rate=1000", sudo=True)
print(mas.scan_result)
```

It should at least return the scanned IP address but it doesn't

Output:
`{"command_line": "masscan -oJ - 0.0.0.0/24 -p 25565 --rate=1000", "scan": {}}`

This is the case with every IP address. I don't know what I'm doing wrong.

**Comment by gsfish** [comment]
I have encountered the same situation as you, and I found that is because masscan with low version (for me is 1.0.4) print invalid json output, so python-masscan just skip parsing it and return an empty dict.

**Comment by Besix2** [comment]
how to fix that

**Comment by BMlovePanda** [comment]
> how to fix that

update masscan from [git ](https://github.com/robertdavidgraham/masscan)
