### ISSUE TITLE
Threading Feature

### ISSUE THREAD

**Issue by arbazkiraak** [MyKings/python-masscan#9]
Hello @MyKings ,

How about adding a threading to masscan for faster result ?

**Comment by MyKings** [comment]
@arbazkiraak 

Sorry, there is no plan to support this feature, but you can control the scanning speed by setting the masscan "--rate" parameter. Note that adjusting this parameter will take up a lot of network bandwidth on your server.

```python
>>> import masscan
>>> mas = masscan.PortScanner()
>>> mas.scan('192.168.168.0.1/24', ports='22,80,8080', arguments='--rate=10000')
[2018-09-17 09:12:06,064] [DEBUG] [masscan.py 10 line] Scan parameters: "masscan -oX - 192.168.0.1/24 -p 22,80,8080 --rate=10000"
 ```
